version: '3.8'

services:
  # PostgreSQL + PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: transporte_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transporte_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transporte_network

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transporte_backend
    env_file:
      - ./backend/.env              # Lee TODAS las variables desde backend/.env (source of truth)
    environment:
      # Overrides específicos para Docker (solo lo que DEBE ser diferente en contenedores)
      - DB_HOST=postgres            # Dentro de Docker, el host es el nombre del servicio postgres
      - DATABASE_URL=postgresql://${DB_USER:-app_user}:${DB_PASSWORD:-app_user}@postgres:5432/${DB_NAME:-transporte_db}
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - transporte_network
    restart: unless-stopped

  # Frontend (Vite dev server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transporte_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - transporte_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  transporte_network:
    driver: bridge
